#!/bin/sh

CLEAN_BRANCHES="$CODEBUILD_GIT_CLEAN_BRANCHES"
GIT_TS="$CODEBUILD_GIT_TIMESTAMP"
GIT_SHA="$CODEBUILD_GIT_SHORT_COMMIT"
SUFFIX="-$GIT_TS-$GIT_SHA"

BRANCH_TAGS="$(echo "$CLEAN_BRANCHES" | sed "s|\$|$SUFFIX|g")"

DOCKER_TAGS="$BRANCH_TAGS"

export DOCKER_TAGS="$GIT_SHA\n$DOCKER_TAGS"
export DOCKER_PULL_TAGS="$GIT_SHA\n$CLEAN_BRANCHES"

echo "==> AWS CodeBuild Docker Environment Variables:"
echo "==> DOCKER_TAGS = $DOCKER_TAGS"
echo "==> DOCKER_PULL_TAGS = $DOCKER_PULL_TAGS"
