#!/bin/sh

export CI=true
export CODEBUILD=true

echo "==> CODEBUILD_SOURCE_VERSION = $CODEBUILD_SOURCE_VERSION"

export CODEBUILD_GIT_BRANCHES="$(git branch -r --points-at HEAD --sort='*authordate')";
echo "CODEBUILD_GIT_BRANCHES: $CODEBUILD_GIT_BRANCHES";
FILTERED_BRANCHES="$(echo "$CODEBUILD_GIT_BRANCHES" | grep $CODEBUILD_SOURCE_VERSION)";
echo "FILTERED_BRANCHES: $FILTERED_BRANCHES";
if [ "$(echo "$FILTERED_BRANCHES" | awk '{$1=$1};1')" != "" ]; then
  echo "We have 1 or more matching branches";
  POSSIBLE_BRANCHES="$FILTERED_BRANCHES";
else
  POSSIBLE_BRANCHES="$CODEBUILD_GIT_BRANCHES";
fi
CODEBUILD_GIT_BRANCH="$(echo "$POSSIBLE_BRANCHES" | head -n1 | awk '{ printf $1 }')";
export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#origin/};

for branch in `echo "$CODEBUILD_GIT_BRANCHES"`; do  echo "---> ${branch#origin/}"; done

export CODEBUILD_GIT_CLEAN_BRANCH="$(echo "$CODEBUILD_GIT_BRANCH" | tr '/' '.')"
export CODEBUILD_GIT_CLEAN_BRANCHES="$(echo "$CODEBUILD_GIT_BRANCHES" | tr '/' '.')"
export CODEBUILD_GIT_MESSAGE="$(git log -1 --pretty=%B)"
export CODEBUILD_GIT_AUTHOR="$(git log -1 --pretty=%an)"
export CODEBUILD_GIT_AUTHOR_EMAIL="$(git log -1 --pretty=%ae)"
export CODEBUILD_GIT_COMMIT="$(git log -1 --pretty=%H)"
export CODEBUILD_GIT_SHORT_COMMIT="$(git log -1 --pretty=%h)"
export CODEBUILD_GIT_TAG="$(git describe --tags --exact-match 2>/dev/null)"
export CODEBUILD_GIT_TIMESTAMP="$(TZ=UTC git show --quiet --date='format-local:%Y%m%d.%H%M%SZ' --format="%cd")"

export CODEBUILD_PULL_REQUEST=false
if [ "${CODEBUILD_SOURCE_VERSION#pr/}" != "$CODEBUILD_SOURCE_VERSION" ] ; then
  export CODEBUILD_PULL_REQUEST=${CODEBUILD_SOURCE_VERSION#pr/};
fi

export CODEBUILD_PROJECT=${CODEBUILD_BUILD_ID%:$CODEBUILD_LOG_PATH}
export CODEBUILD_BUILD_URL=https://$AWS_DEFAULT_REGION.console.aws.amazon.com/codebuild/home?region=$AWS_DEFAULT_REGION#/builds/$CODEBUILD_BUILD_ID/view/new

echo "==> AWS CodeBuild Extra Environment Variables:"
echo "==> CI = $CI"
echo "==> CODEBUILD = $CODEBUILD"
echo "==> CODEBUILD_GIT_AUTHOR = $CODEBUILD_GIT_AUTHOR"
echo "==> CODEBUILD_GIT_AUTHOR_EMAIL = $CODEBUILD_GIT_AUTHOR_EMAIL"
echo "==> CODEBUILD_GIT_BRANCH = $CODEBUILD_GIT_BRANCH"
echo "==> CODEBUILD_GIT_CLEAN_BRANCH = $CODEBUILD_GIT_CLEAN_BRANCH"
echo "==> CODEBUILD_GIT_BRANCHES = $CODEBUILD_GIT_BRANCHES"
echo "==> CODEBUILD_GIT_CLEAN_BRANCHES = $CODEBUILD_GIT_CLEAN_BRANCHES"
echo "==> CODEBUILD_GIT_COMMIT = $CODEBUILD_GIT_COMMIT"
echo "==> CODEBUILD_GIT_SHORT_COMMIT = $CODEBUILD_GIT_SHORT_COMMIT"
echo "==> CODEBUILD_GIT_MESSAGE = $CODEBUILD_GIT_MESSAGE"
echo "==> CODEBUILD_GIT_TAG = $CODEBUILD_GIT_TAG"
echo "==> CODEBUILD_GIT_MOST_RECENT_TAG = $CODEBUILD_GIT_MOST_RECENT_TAG"
echo "==> CODEBUILD_GIT_TIMESTAMP = $CODEBUILD_GIT_TIMESTAMP"
echo "==> CODEBUILD_PROJECT = $CODEBUILD_PROJECT"
echo "==> CODEBUILD_PULL_REQUEST = $CODEBUILD_PULL_REQUEST"
echo "git version: $(git --version)"
